name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-env:
    name: "Build base environment"
    runs-on: ubuntu-latest
    env:
      ROOT: ${GITHUB_WORKSPACE}

    steps:
    - name: Only checkout action scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github

    - name: Checkout UTF-8 library
      uses: actions/checkout@v4
      with:
        repository: arseniuss/flos-libutf8
        path: src/flos/libutf8
      
    - name: Build UTF-8 library
      run: |
        ./bin/update-UnicodeData.bash # non standard
        [ -f ./configure ] && ./configure
        make
        make check
      working-directory: src/flos/libutf8

    - name: Checkout data structures library
      uses: actions/checkout@v4
      with:
        repository: arseniuss/flos-libds
        path: src/flos/libds

    - name: Build data structure library
      run: |
        [ -f ./configure ] && ./configure
        make
        make check
      working-directory: src/flos/libds

    - name: Checkout utils library
      uses: actions/checkout@v4
      with:
        repository: arseniuss/flos-libutils
        path: src/flos/libutils

    - name: Build utils library
      run: |
        [ -f ./configure ] && ./configure
        make
      working-directory: src/flos/libutils

   
       
  normal-build:
    name: "Normal build"
    runs-on: ubuntu-latest
    needs: [build-env]
    steps:
     - name: Checkout POSIX cell compiler
       uses: actions/checkout@v4
       with:
         repository: arseniuss/flos-pcellc
         path: src/flos/pcellc

     - name: Build POSIX cell compiler
       run: |
         [ -f ./configure ] && ./configure
         make
       working-directory: src/flos/pcellc
     

